2020-10-02 10:39:05,353 ERROR 16764 nodejs.ClusterClientNoResponseError: client no response in 2873273ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 16764
hostname: SC-202006081301

2020-10-02 10:39:37,524 ERROR 16764 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 16764
hostname: SC-202006081301

2020-10-02 11:42:21,530 ERROR 16764 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 16764
hostname: SC-202006081301

2020-10-02 14:28:02,366 ERROR 10832 nodejs.ClusterClientNoResponseError: client no response in 83275ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 10832
hostname: SC-202006081301

2020-10-02 19:35:11,017 ERROR 17756 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 17756
hostname: SC-202006081301

2020-10-09 13:58:17,899 ERROR 1716 nodejs.ServerNoResponseError: server 127.0.0.1:52633 no response in 39999ms, maybe the socket is end on the other side. (address: 127.0.0.1:52633)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ServerNoResponseError"
pid: 1716
hostname: SC-202006081301

2020-10-09 14:05:27,344 ERROR 8736 nodejs.ClusterClientNoResponseError: client no response in 489443ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 8736
hostname: SC-202006081301

2020-10-09 14:56:46,231 ERROR 1724 nodejs.unhandledRejectionError: ER_NO_DEFAULT_FOR_FIELD: Field 'level' doesn't have a default value
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `passwd`, `addtimes`, `tel`, `ip`, `mid`) VALUES('crush', 'hsx000000', '2020-10-09 14:56:46.226', '17738177447', '192.168.5.151', 1)
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'level' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`username`, `passwd`, `addtimes`, `tel`, `ip`, `mid`) VALUES('crush', 'hsx000000', '2020-10-09 14:56:46.226', '17738177447', '192.168.5.151', 1)"
name: "unhandledRejectionError"
pid: 1724
hostname: SC-202006081301

2020-10-09 15:18:41,328 ERROR 17420 [-/192.168.5.151/-/3ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:29:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 17420
hostname: SC-202006081301

2020-10-09 15:20:03,854 ERROR 2200 [-/192.168.5.151/-/11ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:30:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 2200
hostname: SC-202006081301

2020-10-09 15:21:34,688 ERROR 9384 [-/192.168.5.151/-/39ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:29:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 9384
hostname: SC-202006081301

2020-10-09 15:22:44,472 ERROR 9384 [-/192.168.5.151/-/8805ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:29:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 9384
hostname: SC-202006081301

2020-10-09 15:22:55,417 ERROR 12204 [-/192.168.5.151/-/37ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:30:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 12204
hostname: SC-202006081301

2020-10-09 15:43:37,050 ERROR 12492 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 12492
hostname: SC-202006081301

2020-10-09 15:49:28,638 ERROR 6100 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'addttimes' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: update user set addttimes = now(),ip='192.168.5.151',passwd='hsx010101' where uid = '18'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'addttimes' in 'field list'"
sqlState: "42S22"
index: 0
sql: "update user set addttimes = now(),ip='192.168.5.151',passwd='hsx010101' where uid = '18'"
name: "unhandledRejectionError"
pid: 6100
hostname: SC-202006081301

2020-10-09 15:49:28,694 ERROR 6100 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'addttimes' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: update user set addttimes = now(),ip='192.168.5.151',passwd='hsx010101' where uid = '18'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'addttimes' in 'field list'"
sqlState: "42S22"
index: 0
sql: "update user set addttimes = now(),ip='192.168.5.151',passwd='hsx010101' where uid = '18'"
name: "unhandledRejectionError"
pid: 6100
hostname: SC-202006081301

2020-10-09 15:50:43,795 ERROR 6100 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'addttimes' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: update user set addttimes = now(),ip='192.168.5.151',passwd='hsx111111' where uid = '18'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'addttimes' in 'field list'"
sqlState: "42S22"
index: 0
sql: "update user set addttimes = now(),ip='192.168.5.151',passwd='hsx111111' where uid = '18'"
name: "unhandledRejectionError"
pid: 6100
hostname: SC-202006081301

2020-10-09 15:51:47,139 ERROR 6100 nodejs.unhandledRejectionError: ER_BAD_FIELD_ERROR: Unknown column 'addttimes' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: update user set addttimes = now(),ip='192.168.5.151',passwd='hsx222222' where uid = '18'
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'addttimes' in 'field list'"
sqlState: "42S22"
index: 0
sql: "update user set addttimes = now(),ip='192.168.5.151',passwd='hsx222222' where uid = '18'"
name: "unhandledRejectionError"
pid: 6100
hostname: SC-202006081301

2020-10-09 15:54:32,631 ERROR 6100 nodejs.ServerNoResponseError: server 127.0.0.1:54797 no response in 20001ms, maybe the socket is end on the other side. (address: 127.0.0.1:54797)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ServerNoResponseError"
pid: 6100
hostname: SC-202006081301

2020-10-09 15:55:30,331 ERROR 12492 nodejs.ClusterClientNoResponseError: client no response in 97694ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 12492
hostname: SC-202006081301

2020-10-09 15:55:36,382 ERROR 12492 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 12492
hostname: SC-202006081301

2020-10-09 17:00:29,835 ERROR 12492 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 12492
hostname: SC-202006081301

2020-10-09 19:26:09,488 ERROR 16960 [-/192.168.5.151/-/1ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:16:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 16960
hostname: SC-202006081301

2020-10-09 19:27:29,140 ERROR 16960 [-/192.168.5.151/-/1ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:16:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 16960
hostname: SC-202006081301

2020-10-09 19:28:09,380 ERROR 16636 [-/192.168.5.151/-/12ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 16636
hostname: SC-202006081301

2020-10-09 19:31:23,233 ERROR 11784 [-/192.168.5.151/-/4ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:35,951 ERROR 11784 [-/192.168.5.151/-/2ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:37,694 ERROR 11784 [-/192.168.5.151/-/2ms GET /getnotice1?count=3] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:40,312 ERROR 11784 [-/192.168.5.151/-/3ms GET /getnotice1?count=4] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:43,846 ERROR 11784 [-/192.168.5.151/-/2ms GET /getnotice1?count=1] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:34:41,396 ERROR 11784 [-/192.168.5.151/-/9643ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:35:03,310 ERROR 6952 [-/192.168.5.151/-/8ms GET /getnotice1?count=2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'author' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT `author`, `title` FROM `notice` WHERE `status` = 1 ORDER BY `created_at` DESC, `id` DESC LIMIT 1, 5
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'author' in 'field list'"
sqlState: "42S22"
index: 0
sql: "SELECT `author`, `title` FROM `notice` WHERE `status` = 1 ORDER BY `created_at` DESC, `id` DESC LIMIT 1, 5"
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6952
hostname: SC-202006081301

2020-10-09 19:35:45,552 ERROR 7548 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 7548
hostname: SC-202006081301

2020-10-10 10:07:05,061 ERROR 14196 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 14196
hostname: SC-202006081301

2020-10-10 12:58:44,523 ERROR 14196 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 14196
hostname: SC-202006081301

2020-10-10 14:00:26,755 ERROR 14196 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 14196
hostname: SC-202006081301

2020-10-10 15:35:24,556 ERROR 12780 nodejs.ClusterClientNoResponseError: client no response in 66682ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 12780
hostname: SC-202006081301

2020-10-10 16:40:48,594 ERROR 13412 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 13412
hostname: SC-202006081301

2020-10-10 17:15:21,132 ERROR 8244 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'username' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `passwd`, `addtimes`, `tel`, `ip`, `mid`) VALUES(NULL, NULL, '2020-10-10 17:15:21.126', NULL, '192.168.5.151', 1)
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'username' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `passwd`, `addtimes`, `tel`, `ip`, `mid`) VALUES(NULL, NULL, '2020-10-10 17:15:21.126', NULL, '192.168.5.151', 1)"
name: "unhandledRejectionError"
pid: 8244
hostname: SC-202006081301

2020-10-10 17:15:36,060 ERROR 8244 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'username' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `passwd`, `addtimes`, `tel`, `ip`, `mid`) VALUES(NULL, NULL, '2020-10-10 17:15:36.058', NULL, '192.168.5.151', 1)
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'username' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `user`(`username`, `passwd`, `addtimes`, `tel`, `ip`, `mid`) VALUES(NULL, NULL, '2020-10-10 17:15:36.058', NULL, '192.168.5.151', 1)"
name: "unhandledRejectionError"
pid: 8244
hostname: SC-202006081301

2020-10-10 17:44:07,408 ERROR 17656 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 17656
hostname: SC-202006081301

2020-10-10 17:46:17,162 ERROR 19540 [-/192.168.5.151/-/2ms POST /upload] nodejs.TypeError: Cannot read property '0' of undefined
    at UploadController.index (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\upload.js:10:37)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 19540
hostname: SC-202006081301

2020-10-10 20:08:55,904 ERROR 17836 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 17836
hostname: SC-202006081301

2020-10-10 20:09:47,858 ERROR 2484 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'mid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`) VALUES('法法', NULL, '2020-10-10 20:09:47.846', '发斯蒂芬', NULL, 'http://192.168.5.151:88/public/uploads/2ffdfd3a-2de7-4de1-9a0f-e67d28bef816.jpg', '6')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'mid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`) VALUES('法法', NULL, '2020-10-10 20:09:47.846', '发斯蒂芬', NULL, 'http://192.168.5.151:88/public/uploads/2ffdfd3a-2de7-4de1-9a0f-e67d28bef816.jpg', '6')"
name: "unhandledRejectionError"
pid: 2484
hostname: SC-202006081301

2020-10-10 20:10:27,399 ERROR 21404 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`) VALUES('法法', 1, '2020-10-10 20:10:27.391', '发斯蒂芬', NULL, 'http://192.168.5.151:88/public/uploads/2ffdfd3a-2de7-4de1-9a0f-e67d28bef816.jpg', '6')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`) VALUES('法法', 1, '2020-10-10 20:10:27.391', '发斯蒂芬', NULL, 'http://192.168.5.151:88/public/uploads/2ffdfd3a-2de7-4de1-9a0f-e67d28bef816.jpg', '6')"
name: "unhandledRejectionError"
pid: 21404
hostname: SC-202006081301

2020-10-10 20:10:57,649 ERROR 13304 nodejs.unhandledRejectionError: ER_NO_DEFAULT_FOR_FIELD: Field 'condition' doesn't have a default value
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`) VALUES('法法', 1, '2020-10-10 20:10:57.641', '发斯蒂芬', 1, 'http://192.168.5.151:88/public/uploads/2ffdfd3a-2de7-4de1-9a0f-e67d28bef816.jpg', '6')
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'condition' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`) VALUES('法法', 1, '2020-10-10 20:10:57.641', '发斯蒂芬', 1, 'http://192.168.5.151:88/public/uploads/2ffdfd3a-2de7-4de1-9a0f-e67d28bef816.jpg', '6')"
name: "unhandledRejectionError"
pid: 13304
hostname: SC-202006081301

2020-10-12 08:52:25,668 ERROR 6596 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'mid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('废物', NULL, '2020-10-12 08:52:25.663', '不好看', 1, 'http://192.168.5.151:88/public/uploads/3c1abf24-7a4d-4135-9b2d-0d29e02661bd.jpg', '4', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'mid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('废物', NULL, '2020-10-12 08:52:25.663', '不好看', 1, 'http://192.168.5.151:88/public/uploads/3c1abf24-7a4d-4135-9b2d-0d29e02661bd.jpg', '4', '1')"
name: "unhandledRejectionError"
pid: 6596
hostname: SC-202006081301

2020-10-12 08:53:58,512 ERROR 9332 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('废物', 1, '2020-10-12 08:53:58.499', '不好看', NULL, 'http://192.168.5.151:88/public/uploads/3c1abf24-7a4d-4135-9b2d-0d29e02661bd.jpg', '4', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('废物', 1, '2020-10-12 08:53:58.499', '不好看', NULL, 'http://192.168.5.151:88/public/uploads/3c1abf24-7a4d-4135-9b2d-0d29e02661bd.jpg', '4', '1')"
name: "unhandledRejectionError"
pid: 9332
hostname: SC-202006081301

2020-10-12 08:53:58,522 ERROR 9332 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('废物', 1, '2020-10-12 08:53:58.508', '不好看', NULL, 'http://192.168.5.151:88/public/uploads/3c1abf24-7a4d-4135-9b2d-0d29e02661bd.jpg', '4', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('废物', 1, '2020-10-12 08:53:58.508', '不好看', NULL, 'http://192.168.5.151:88/public/uploads/3c1abf24-7a4d-4135-9b2d-0d29e02661bd.jpg', '4', '1')"
name: "unhandledRejectionError"
pid: 9332
hostname: SC-202006081301

2020-10-12 08:58:28,916 ERROR 15532 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('haokande', 1, '2020-10-12 08:58:28.910', 'buhaokan', NULL, 'http://192.168.5.151:88/public/uploads/4955adc3-cda4-4a5d-8515-5b58f936d6aa.jpg', '4', '2')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('haokande', 1, '2020-10-12 08:58:28.910', 'buhaokan', NULL, 'http://192.168.5.151:88/public/uploads/4955adc3-cda4-4a5d-8515-5b58f936d6aa.jpg', '4', '2')"
name: "unhandledRejectionError"
pid: 15532
hostname: SC-202006081301

2020-10-12 09:05:06,777 ERROR 11432 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:05:06.771', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:05:06.771', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')"
name: "unhandledRejectionError"
pid: 11432
hostname: SC-202006081301

2020-10-12 09:06:58,408 ERROR 21260 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:06:58.401', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:06:58.401', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')"
name: "unhandledRejectionError"
pid: 21260
hostname: SC-202006081301

2020-10-12 09:08:26,404 ERROR 17652 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:08:26.396', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:08:26.396', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')"
name: "unhandledRejectionError"
pid: 17652
hostname: SC-202006081301

2020-10-12 09:17:51,898 ERROR 7508 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:17:51.891', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasf', 1, '2020-10-12 09:17:51.891', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/624c75bc-9820-48ac-b82b-d4da785c7664.jpg', '2', '2')"
name: "unhandledRejectionError"
pid: 7508
hostname: SC-202006081301

2020-10-12 09:19:39,595 ERROR 21448 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('32123', 1, '2020-10-12 09:19:39.589', '21412', NULL, 'http://192.168.5.151:88/public/uploads/f86f7fc9-8baa-42e1-ae80-679ae978cf40.jpg', '2', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('32123', 1, '2020-10-12 09:19:39.589', '21412', NULL, 'http://192.168.5.151:88/public/uploads/f86f7fc9-8baa-42e1-ae80-679ae978cf40.jpg', '2', '1')"
name: "unhandledRejectionError"
pid: 21448
hostname: SC-202006081301

2020-10-12 10:08:44,465 ERROR 20664 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasfa', 1, '2020-10-12 10:08:44.377', 'fasfas', NULL, 'http://192.168.5.151:88/public/uploads/31b44c8b-1c90-42cc-91f8-be8cc5bd7fcd.jpg', '3', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fasfa', 1, '2020-10-12 10:08:44.377', 'fasfas', NULL, 'http://192.168.5.151:88/public/uploads/31b44c8b-1c90-42cc-91f8-be8cc5bd7fcd.jpg', '3', '1')"
name: "unhandledRejectionError"
pid: 20664
hostname: SC-202006081301

2020-10-13 14:47:54,209 ERROR 6068 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('manhuawang', 1, '2020-10-13 14:47:54.108', 'sadasda', NULL, 'http://192.168.5.151:88/public/uploads/1672d417-58e3-434d-9f34-cb44b7a2ed2c.jpg', '4', '2')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('manhuawang', 1, '2020-10-13 14:47:54.108', 'sadasda', NULL, 'http://192.168.5.151:88/public/uploads/1672d417-58e3-434d-9f34-cb44b7a2ed2c.jpg', '4', '2')"
name: "unhandledRejectionError"
pid: 6068
hostname: SC-202006081301

2020-10-13 14:53:53,426 ERROR 15336 [-/192.168.5.151/-/30ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15336
hostname: SC-202006081301

2020-10-13 14:53:56,693 ERROR 15336 [-/192.168.5.151/-/2ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15336
hostname: SC-202006081301

2020-10-13 14:54:48,985 ERROR 15644 [-/192.168.5.151/-/26ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15644
hostname: SC-202006081301

2020-10-13 15:01:22,461 ERROR 8588 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('不好看的漫画', 1, '2020-10-13 15:01:22.454', '好看的漫画', NULL, 'http://192.168.5.151:88/public/uploads/31467fd0-0dcb-41cb-aa80-5603673bb37c.jpg', '4', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('不好看的漫画', 1, '2020-10-13 15:01:22.454', '好看的漫画', NULL, 'http://192.168.5.151:88/public/uploads/31467fd0-0dcb-41cb-aa80-5603673bb37c.jpg', '4', '1')"
name: "unhandledRejectionError"
pid: 8588
hostname: SC-202006081301

2020-10-13 15:04:54,559 ERROR 14864 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('不好看的漫画', 1, '2020-10-13 15:04:54.553', '好看的漫画', NULL, 'http://192.168.5.151:88/public/uploads/8f4ccdb0-91c8-4935-9f24-d0823ef9e230.jpg', '6', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('不好看的漫画', 1, '2020-10-13 15:04:54.553', '好看的漫画', NULL, 'http://192.168.5.151:88/public/uploads/8f4ccdb0-91c8-4935-9f24-d0823ef9e230.jpg', '6', '1')"
name: "unhandledRejectionError"
pid: 14864
hostname: SC-202006081301

2020-10-13 15:07:11,333 ERROR 15720 [-/192.168.5.151/-/32ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15720
hostname: SC-202006081301

2020-10-13 15:46:12,094 ERROR 15976 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 15976
hostname: SC-202006081301

2020-10-13 15:50:08,750 ERROR 8356 [-/192.168.5.151/-/32ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 8356
hostname: SC-202006081301

2020-10-13 15:55:27,595 ERROR 9796 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('huangfff', 1, '2020-10-13 15:55:27.590', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/57a37114-ca81-4bd0-ae82-b4f123a9d3c1.jpg', '3', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('huangfff', 1, '2020-10-13 15:55:27.590', 'fada', NULL, 'http://192.168.5.151:88/public/uploads/57a37114-ca81-4bd0-ae82-b4f123a9d3c1.jpg', '3', '1')"
name: "unhandledRejectionError"
pid: 9796
hostname: SC-202006081301

2020-10-13 15:58:17,789 ERROR 1492 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fafasf', 1, '2020-10-13 15:58:17.782', 'fadas', NULL, 'http://192.168.5.151:88/public/uploads/b50e21fe-93a0-4965-8d80-e519b567e82c.jpg', '3', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fafasf', 1, '2020-10-13 15:58:17.782', 'fadas', NULL, 'http://192.168.5.151:88/public/uploads/b50e21fe-93a0-4965-8d80-e519b567e82c.jpg', '3', '1')"
name: "unhandledRejectionError"
pid: 1492
hostname: SC-202006081301

2020-10-13 15:59:54,356 ERROR 15056 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('gfafa', 1, '2020-10-13 15:59:54.345', 'fasfa', NULL, 'http://192.168.5.151:88/public/uploads/7f3f56c1-437d-4d59-9601-8e17d1dbd800.jpg', '3', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('gfafa', 1, '2020-10-13 15:59:54.345', 'fasfa', NULL, 'http://192.168.5.151:88/public/uploads/7f3f56c1-437d-4d59-9601-8e17d1dbd800.jpg', '3', '1')"
name: "unhandledRejectionError"
pid: 15056
hostname: SC-202006081301

2020-10-13 16:03:01,839 ERROR 15976 nodejs.ClusterClientNoResponseError: client no response in 77754ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 15976
hostname: SC-202006081301

2020-10-13 16:12:23,868 ERROR 14808 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('dnasjhdu', 1, '2020-10-13 16:12:23.861', 'fasdas', NULL, 'http://192.168.5.151:88/public/uploads/f3e5c5f6-89b1-4ca7-a043-bbe26f1f3407.jpg', '7', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('dnasjhdu', 1, '2020-10-13 16:12:23.861', 'fasdas', NULL, 'http://192.168.5.151:88/public/uploads/f3e5c5f6-89b1-4ca7-a043-bbe26f1f3407.jpg', '7', '1')"
name: "unhandledRejectionError"
pid: 14808
hostname: SC-202006081301

2020-10-13 16:23:59,412 ERROR 15392 [-/192.168.5.151/-/39ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15392
hostname: SC-202006081301

2020-10-13 16:25:34,336 ERROR 15392 nodejs.unhandledRejectionError: ER_BAD_NULL_ERROR: Column 'uid' cannot be null
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fafhas', 1, '2020-10-13 16:25:34.330', 'adsad', NULL, 'http://192.168.5.151:88/public/uploads/5f4515d3-00e1-4ba1-9d21-cf0e0d4edfd1.jpg', '6', '1')
code: "ER_BAD_NULL_ERROR"
errno: 1048
sqlMessage: "Column 'uid' cannot be null"
sqlState: "23000"
index: 0
sql: "INSERT INTO `comics`(`title`, `mid`, `addtimes`, `intro`, `uid`, `cover`, `tid`, `condition`) VALUES('fafhas', 1, '2020-10-13 16:25:34.330', 'adsad', NULL, 'http://192.168.5.151:88/public/uploads/5f4515d3-00e1-4ba1-9d21-cf0e0d4edfd1.jpg', '6', '1')"
name: "unhandledRejectionError"
pid: 15392
hostname: SC-202006081301

2020-10-28 16:35:13,698 ERROR 23088 nodejs.ServerNoResponseError: server 127.0.0.1:7390 no response in 20001ms, maybe the socket is end on the other side. (address: 127.0.0.1:7390)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ServerNoResponseError"
pid: 23088
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:18:33,809 ERROR 28480 nodejs.ClusterClientNoResponseError: client no response in 2640103ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 28480
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:48:13,631 ERROR 28952 [-/127.0.0.1/-/2ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28952
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:48:29,346 ERROR 28952 [-/127.0.0.1/-/0ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28952
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:48:51,301 ERROR 28952 [-/127.0.0.1/-/1ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28952
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:49:42,400 ERROR 29508 [-/127.0.0.1/-/30ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:7:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29508
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:51:25,364 ERROR 28768 [-/127.0.0.1/-/23ms POST /userlogin] nodejs.ReferenceError: user is not defined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:15)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28768
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:54:18,437 ERROR 19896 [-/127.0.0.1/-/44ms POST /userlogin] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: select *  from user where username=undefined
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select *  from user where username=undefined"
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19896
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:54:35,479 ERROR 23272 [-/127.0.0.1/-/34ms POST /userlogin] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'lisa' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: select *  from user where username=lisa
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'lisa' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select *  from user where username=lisa"
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 23272
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:55:35,428 ERROR 30724 [-/127.0.0.1/-/35ms POST /userlogin] nodejs.ReferenceError: user is not defined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:14:4)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:11:13)
    at async C:\Users\Administrator\Desktop\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\server\node_modules\_koa-session@6.1.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 30724
hostname: BN6BA2A2TJYV3R8

2020-10-28 19:21:57,283 ERROR 29832 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 29832
hostname: BN6BA2A2TJYV3R8

2020-10-29 09:58:14,116 ERROR 24360 nodejs.ClusterClientNoResponseError: client no response in 78456ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 24360
hostname: BN6BA2A2TJYV3R8

2020-10-29 10:00:34,646 ERROR 7256 nodejs.ECONNABORTEDError: write ECONNABORTED (address: 127.0.0.1:1547)
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Follower.sendHeartBeat (C:\Users\Administrator\Desktop\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:105:18)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:437:12)
    at listOnTimeout (internal/timers.js:549:17)
errno: "ECONNABORTED"
code: "ECONNABORTED"
syscall: "write"
name: "ECONNABORTEDError"
pid: 7256
hostname: BN6BA2A2TJYV3R8

2020-10-29 11:37:27,284 ERROR 26588 [-/127.0.0.1/-/4ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 26588
hostname: BN6BA2A2TJYV3R8

2020-10-29 11:39:24,768 ERROR 26588 [-/127.0.0.1/-/2ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 26588
hostname: BN6BA2A2TJYV3R8

2020-10-29 13:59:50,367 ERROR 24360 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 24360
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:31:54,797 ERROR 21124 [-/127.0.0.1/-/76ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 21124
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:46:21,004 ERROR 14544 [-/127.0.0.1/-/20ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:46:24,348 ERROR 14544 [-/127.0.0.1/-/3ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:50:43,126 ERROR 14544 nodejs.ServerNoResponseError: server 127.0.0.1:1547 no response in 40001ms, maybe the socket is end on the other side. (address: 127.0.0.1:1547)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:427:21)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ServerNoResponseError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,114 ERROR 24360 nodejs.ClusterClientNoResponseError: client no response in 154986ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 24360
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,171 ERROR 14544 [-/127.0.0.1/-/30ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,175 ERROR 14544 [-/127.0.0.1/-/44ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,185 ERROR 14544 [-/127.0.0.1/-/37ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:56:16,228 ERROR 19928 [-/127.0.0.1/-/9ms POST /userreg] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('lee', 'q123456_', '男', '13598744130')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('lee', 'q123456_', '男', '13598744130')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19928
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:57:09,644 ERROR 19928 [-/127.0.0.1/-/3ms POST /userreg] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('zzz', 'sdas123_', '男', '18108340587')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('zzz', 'sdas123_', '男', '18108340587')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19928
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:05:01,242 ERROR 24360 nodejs.unhandledExceptionError: read ECONNRESET
    at TCP.onStreamRead (internal/stream_base_commons.js:205:27)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "read"
name: "unhandledExceptionError"
pid: 24360
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:05:19,521 ERROR 29112 [-/127.0.0.1/-/21ms POST /userreg] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})' at line 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ({username:'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})' at line 1"
sqlState: "42000"
index: 0
sql: "INSERT INTO user VALUES ({username:'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 29112
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:06:56,117 ERROR 11384 [-/127.0.0.1/-/39ms POST /userreg] nodejs.ER_DATA_TOO_LONGError: ER_DATA_TOO_LONG: Data too long for column 'tel' at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('data.name', 'data.tellphone', 'data.gender', 'data.password')
code: "ER_DATA_TOO_LONG"
errno: 1406
sqlMessage: "Data too long for column 'tel' at row 1"
sqlState: "22001"
index: 0
sql: "INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('data.name', 'data.tellphone', 'data.gender', 'data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_DATA_TOO_LONGError"
pid: 11384
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:07:56,220 ERROR 20292 [-/127.0.0.1/-/18ms POST /userreg] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'birthday' doesn't have a default value
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('zzz', '18108340587', '男', 'sdas123_')
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'birthday' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('zzz', '18108340587', '男', 'sdas123_')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 20292
hostname: BN6BA2A2TJYV3R8

2020-10-30 10:26:18,007 ERROR 8360 [-/192.168.5.151/-/141ms POST /upload] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\a76b4ac0-8582-40b6-886b-4fede140b371.mp4' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/mp4/a76b4ac0-8582-40b6-886b-4fede140b371.mp4'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.index (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:12:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\a76b4ac0-8582-40b6-886b-4fede140b371.mp4"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/mp4/a76b4ac0-8582-40b6-886b-4fede140b371.mp4"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:26:22,805 ERROR 8360 [-/192.168.5.151/-/7ms POST /uploads] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/img/d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.indexs (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:21:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/img/d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:26:26,849 ERROR 8360 [-/192.168.5.151/-/5ms POST /uploads] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/img/f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.indexs (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:21:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/img/f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:26:38,904 ERROR 8360 [-/192.168.5.151/-/5ms POST /uploads] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/img/3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.indexs (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:21:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/img/3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:28:07,816 ERROR 18116 nodejs.EPERMError: EPERM: operation not permitted, watch
    at FSEvent.FSWatcher._handle.onchange (internal/fs/watchers.js:127:28)
errno: -4048
syscall: "watch"
code: "EPERM"
filename: null
dir: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app\\public\\mp4\\img"
name: "EPERMError"
pid: 18116
hostname: SC-202006081301

2020-10-30 10:40:10,571 ERROR 8360 [-/undefined/-/132ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNABORTEDError: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at clearBuffer (_stream_writable.js:542:7)
    at Socket.Writable.uncork (_stream_writable.js:338:7)
    at ServerResponse.OutgoingMessage.uncork (_http_outgoing.js:244:17)
    at connectionCorkNT (_http_outgoing.js:690:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
errno: "ECONNABORTED"
code: "ECONNABORTED"
syscall: "write"
headerSent: true
name: "ECONNABORTEDError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:40:29,572 ERROR 8360 [-/undefined/-/307ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:44:29,642 ERROR 8360 [-/undefined/-/201ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:45:45,851 ERROR 18116 nodejs.ClusterClientNoResponseError: client no response in 76637ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_cluster-client@3.0.1@cluster-client\lib\leader.js:77:23)
    at listOnTimeout (internal/timers.js:549:17)
    at processTimers (internal/timers.js:492:7)
name: "ClusterClientNoResponseError"
pid: 18116
hostname: SC-202006081301

2020-10-30 10:51:57,585 ERROR 8360 nodejs.ECONNABORTEDError: write ECONNABORTED (address: 127.0.0.1:52591)
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at writeOrBuffer (_stream_writable.js:387:5)
    at Socket.Writable.write (_stream_writable.js:318:11)
    at Follower.sendHeartBeat (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:105:18)
    at Timeout._onTimeout (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_tcp-base@3.1.0@tcp-base\lib\base.js:437:12)
    at listOnTimeout (internal/timers.js:549:17)
errno: "ECONNABORTED"
code: "ECONNABORTED"
syscall: "write"
name: "ECONNABORTEDError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:51:57,609 ERROR 8360 [-/undefined/-/14ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNABORTEDError: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at clearBuffer (_stream_writable.js:542:7)
    at Socket.Writable.uncork (_stream_writable.js:338:7)
    at ServerResponse.OutgoingMessage.uncork (_http_outgoing.js:244:17)
    at connectionCorkNT (_http_outgoing.js:690:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
errno: "ECONNABORTED"
code: "ECONNABORTED"
syscall: "write"
headerSent: true
name: "ECONNABORTEDError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:51:57,954 ERROR 8360 [-/undefined/-/287ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:53:32,302 ERROR 8360 [-/undefined/-/120ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 16:28:57,852 ERROR 10180 [-/undefined/-/309ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 10180
hostname: SC-202006081301

