2020-10-09 15:18:41,329 ERROR 17420 [-/192.168.5.151/-/3ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:29:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 17420
hostname: SC-202006081301

2020-10-09 15:20:03,858 ERROR 2200 [-/192.168.5.151/-/11ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:30:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 2200
hostname: SC-202006081301

2020-10-09 15:21:34,690 ERROR 9384 [-/192.168.5.151/-/39ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:29:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 9384
hostname: SC-202006081301

2020-10-09 15:22:44,475 ERROR 9384 [-/192.168.5.151/-/8805ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:29:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 9384
hostname: SC-202006081301

2020-10-09 15:22:55,418 ERROR 12204 [-/192.168.5.151/-/37ms POST /resetpasswd2] nodejs.TypeError: Cannot read property 'tel' of undefined
    at ResetpasswdController.resetpasswd2 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\resetpasswd.js:30:33)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 12204
hostname: SC-202006081301

2020-10-09 19:26:09,490 ERROR 16960 [-/192.168.5.151/-/1ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:16:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 16960
hostname: SC-202006081301

2020-10-09 19:27:35,976 ERROR 16960 [-/192.168.5.151/-/1ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:16:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 16960
hostname: SC-202006081301

2020-10-09 19:28:09,381 ERROR 16636 [-/192.168.5.151/-/12ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 16636
hostname: SC-202006081301

2020-10-09 19:31:23,235 ERROR 11784 [-/192.168.5.151/-/4ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:35,953 ERROR 11784 [-/192.168.5.151/-/2ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:37,696 ERROR 11784 [-/192.168.5.151/-/2ms GET /getnotice1?count=3] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:40,313 ERROR 11784 [-/192.168.5.151/-/3ms GET /getnotice1?count=4] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:32:43,847 ERROR 11784 [-/192.168.5.151/-/2ms GET /getnotice1?count=1] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:34:41,398 ERROR 11784 [-/192.168.5.151/-/9643ms GET /getnotice1?count=2] nodejs.TypeError: Cannot read property 'count' of undefined
    at Notice_Service.findnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\service\notice_.js:17:24)
    at NoticeController.getnotice1 (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\notice.js:17:44)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 11784
hostname: SC-202006081301

2020-10-09 19:35:03,312 ERROR 6952 [-/192.168.5.151/-/8ms GET /getnotice1?count=2] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'author' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: SELECT `author`, `title` FROM `notice` WHERE `status` = 1 ORDER BY `created_at` DESC, `id` DESC LIMIT 1, 5
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'author' in 'field list'"
sqlState: "42S22"
index: 0
sql: "SELECT `author`, `title` FROM `notice` WHERE `status` = 1 ORDER BY `created_at` DESC, `id` DESC LIMIT 1, 5"
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 6952
hostname: SC-202006081301

2020-10-10 17:46:17,163 ERROR 19540 [-/192.168.5.151/-/2ms POST /upload] nodejs.TypeError: Cannot read property '0' of undefined
    at UploadController.index (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\upload.js:10:37)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:36:12
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 19540
hostname: SC-202006081301

2020-10-13 14:53:53,427 ERROR 15336 [-/192.168.5.151/-/30ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15336
hostname: SC-202006081301

2020-10-13 14:53:56,694 ERROR 15336 [-/192.168.5.151/-/2ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15336
hostname: SC-202006081301

2020-10-13 14:54:48,986 ERROR 15644 [-/192.168.5.151/-/26ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15644
hostname: SC-202006081301

2020-10-13 15:07:11,334 ERROR 15720 [-/192.168.5.151/-/32ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15720
hostname: SC-202006081301

2020-10-13 15:50:08,755 ERROR 8356 [-/192.168.5.151/-/32ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 8356
hostname: SC-202006081301

2020-10-13 16:23:59,418 ERROR 15392 [-/192.168.5.151/-/39ms POST /userlogin] nodejs.TypeError: codereg.test is not a function
    at LoginController.userindex (C:\Users\Administrator\Desktop\js笔记\object\server\app\controller\login.js:63:29)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-session@6.0.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
    at async C:\Users\Administrator\Desktop\js笔记\object\server\node_modules\_koa-static-cache@5.1.4@koa-static-cache\index.js:39:63
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 15392
hostname: SC-202006081301

2020-10-28 17:18:33,824 WARN 23088 A client (::1:7763) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,831 WARN 23088 A client (::1:7783) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,837 WARN 23088 A client (::1:7841) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,844 WARN 23088 A client (::1:7877) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,899 WARN 23088 A client (::1:10193) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,902 WARN 23088 A client (::1:10196) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,906 WARN 23088 A client (::1:10204) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,908 WARN 23088 A client (::1:10239) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,911 WARN 23088 A client (::1:10242) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,913 WARN 23088 A client (::1:10248) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,918 WARN 23088 A client (::1:10259) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,921 WARN 23088 A client (::1:10299) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,923 WARN 23088 A client (::1:10323) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,926 WARN 23088 A client (::1:10424) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,927 WARN 23088 A client (::1:10431) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,932 WARN 23088 A client (::1:10454) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,935 WARN 23088 A client (::1:10455) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,937 WARN 23088 A client (::1:10457) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,944 WARN 23088 A client (::1:10458) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,947 WARN 23088 A client (::1:10462) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,949 WARN 23088 A client (::1:10472) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,953 WARN 23088 A client (::1:10502) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,955 WARN 23088 A client (::1:10505) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,957 WARN 23088 A client (::1:10507) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:18:33,959 WARN 23088 A client (::1:10808) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:27:48,326 WARN 6276 A client (::1:11719) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:27:48,328 WARN 6276 A client (::1:11719) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:27:48,329 WARN 6276 A client (::1:11720) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:27:48,330 WARN 6276 A client (::1:11720) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:48:13,637 ERROR 28952 [-/127.0.0.1/-/2ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28952
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:48:29,347 ERROR 28952 [-/127.0.0.1/-/0ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28952
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:48:51,301 ERROR 28952 [-/127.0.0.1/-/1ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28952
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:49:42,401 ERROR 29508 [-/127.0.0.1/-/30ms POST /userlogin] nodejs.TypeError: Cannot read property 'name' of undefined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:7:86)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 29508
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:51:25,366 ERROR 28768 [-/127.0.0.1/-/23ms POST /userlogin] nodejs.ReferenceError: user is not defined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:6:15)
    at UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:9:36)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 28768
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:54:18,439 ERROR 19896 [-/127.0.0.1/-/44ms POST /userlogin] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'undefined' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: select *  from user where username=undefined
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'undefined' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select *  from user where username=undefined"
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19896
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:54:35,480 ERROR 23272 [-/127.0.0.1/-/34ms POST /userlogin] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'lisa' in 'where clause'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: select *  from user where username=lisa
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'lisa' in 'where clause'"
sqlState: "42S22"
index: 0
sql: "select *  from user where username=lisa"
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 23272
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:55:35,430 ERROR 30724 [-/127.0.0.1/-/35ms POST /userlogin] nodejs.ReferenceError: user is not defined
    at UserService.login (C:\Users\Administrator\Desktop\server\app\service\user.js:14:4)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async UserController.login (C:\Users\Administrator\Desktop\server\app\controller\userlogin.js:11:13)
    at async C:\Users\Administrator\Desktop\server\node_modules\_egg-development@2.7.0@egg-development\app\middleware\egg_loader_trace.js:9:50
    at async xframe (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xframe.js:7:5)
    at async xssProtection (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\xssProtection.js:7:5)
    at async nosniff (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\nosniff.js:8:5)
    at async noopen (C:\Users\Administrator\Desktop\server\node_modules\_egg-security@2.8.0@egg-security\lib\middlewares\noopen.js:8:5)
    at async session (C:\Users\Administrator\Desktop\server\node_modules\_koa-session@6.1.0@koa-session\index.js:41:7)
    at async bodyParser (C:\Users\Administrator\Desktop\server\node_modules\_koa-bodyparser@4.3.0@koa-bodyparser\index.js:95:5)
headers: {"Access-Control-Allow-Origin":"http://localhost","Access-Control-Allow-Credentials":"true","vary":"Origin"}
pid: 30724
hostname: BN6BA2A2TJYV3R8

2020-10-28 17:56:40,729 WARN 4588 A client (127.0.0.1:13464) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:40,731 WARN 4588 A client (127.0.0.1:13464) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:40,980 WARN 4588 A client (127.0.0.1:13466) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:40,981 WARN 4588 A client (127.0.0.1:13466) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:41,034 WARN 4588 A client (127.0.0.1:13468) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:41,035 WARN 4588 A client (127.0.0.1:13468) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:41,284 WARN 4588 A client (127.0.0.1:13470) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:56:41,285 WARN 4588 A client (127.0.0.1:13470) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,240 WARN 28856 A client (127.0.0.1:13540) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,241 WARN 28856 A client (127.0.0.1:13540) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,489 WARN 28856 A client (127.0.0.1:13543) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,491 WARN 28856 A client (127.0.0.1:13543) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,544 WARN 28856 A client (127.0.0.1:13545) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,545 WARN 28856 A client (127.0.0.1:13545) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,794 WARN 28856 A client (127.0.0.1:13546) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:57:51,795 WARN 28856 A client (127.0.0.1:13546) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,207 WARN 10720 A client (127.0.0.1:13586) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,209 WARN 10720 A client (127.0.0.1:13586) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,458 WARN 10720 A client (127.0.0.1:13588) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,459 WARN 10720 A client (127.0.0.1:13588) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,512 WARN 10720 A client (127.0.0.1:13590) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,513 WARN 10720 A client (127.0.0.1:13590) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,761 WARN 10720 A client (127.0.0.1:13591) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:28,762 WARN 10720 A client (127.0.0.1:13591) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:32,952 WARN 10720 A client (127.0.0.1:13599) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:32,953 WARN 10720 A client (127.0.0.1:13599) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:33,203 WARN 10720 A client (127.0.0.1:13601) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:33,204 WARN 10720 A client (127.0.0.1:13601) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:33,256 WARN 10720 A client (127.0.0.1:13603) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:33,257 WARN 10720 A client (127.0.0.1:13603) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:33,506 WARN 10720 A client (127.0.0.1:13604) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:58:33,507 WARN 10720 A client (127.0.0.1:13604) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:02,947 WARN 31020 A client (127.0.0.1:13640) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:02,949 WARN 31020 A client (127.0.0.1:13640) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:03,208 WARN 31020 A client (127.0.0.1:13642) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:03,210 WARN 31020 A client (127.0.0.1:13642) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:03,251 WARN 31020 A client (127.0.0.1:13644) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:03,252 WARN 31020 A client (127.0.0.1:13644) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:03,512 WARN 31020 A client (127.0.0.1:13645) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:03,513 WARN 31020 A client (127.0.0.1:13645) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,414 WARN 31020 A client (127.0.0.1:13685) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,415 WARN 31020 A client (127.0.0.1:13685) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,666 WARN 31020 A client (127.0.0.1:13687) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,667 WARN 31020 A client (127.0.0.1:13687) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,717 WARN 31020 A client (127.0.0.1:13689) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,718 WARN 31020 A client (127.0.0.1:13689) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,970 WARN 31020 A client (127.0.0.1:13690) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-28 17:59:23,970 WARN 31020 A client (127.0.0.1:13690) error [HPE_INVALID_METHOD] occurred: Parse Error: Invalid method encountered
2020-10-29 11:37:27,285 ERROR 26588 [-/127.0.0.1/-/4ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 26588
hostname: BN6BA2A2TJYV3R8

2020-10-29 11:39:24,770 ERROR 26588 [-/127.0.0.1/-/2ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 26588
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:31:54,799 ERROR 21124 [-/127.0.0.1/-/76ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 21124
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:46:21,006 ERROR 14544 [-/127.0.0.1/-/20ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:46:24,351 ERROR 14544 [-/127.0.0.1/-/3ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,173 ERROR 14544 [-/127.0.0.1/-/30ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,182 ERROR 14544 [-/127.0.0.1/-/44ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:52:18,188 ERROR 14544 [-/127.0.0.1/-/37ms POST /userreg] nodejs.ER_WRONG_VALUE_COUNT_ON_ROWError: ER_WRONG_VALUE_COUNT_ON_ROW: Column count doesn't match value count at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')
code: "ER_WRONG_VALUE_COUNT_ON_ROW"
errno: 1136
sqlMessage: "Column count doesn't match value count at row 1"
sqlState: "21S01"
index: 0
sql: "INSERT INTO user VALUES ('data.name','data.tellphone','data.gender','data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_WRONG_VALUE_COUNT_ON_ROWError"
pid: 14544
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:56:16,229 ERROR 19928 [-/127.0.0.1/-/9ms POST /userreg] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('lee', 'q123456_', '男', '13598744130')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('lee', 'q123456_', '男', '13598744130')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19928
hostname: BN6BA2A2TJYV3R8

2020-10-29 14:57:09,647 ERROR 19928 [-/127.0.0.1/-/3ms POST /userreg] nodejs.ER_BAD_FIELD_ERRORError: ER_BAD_FIELD_ERROR: Unknown column 'name' in 'field list'
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('zzz', 'sdas123_', '男', '18108340587')
code: "ER_BAD_FIELD_ERROR"
errno: 1054
sqlMessage: "Unknown column 'name' in 'field list'"
sqlState: "42S22"
index: 0
sql: "INSERT INTO `user`(`name`, `password`, `gender`, `tellphone`) VALUES('zzz', 'sdas123_', '男', '18108340587')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_BAD_FIELD_ERRORError"
pid: 19928
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:05:19,522 ERROR 29112 [-/127.0.0.1/-/21ms POST /userreg] nodejs.ER_PARSE_ERRORError: ER_PARSE_ERROR: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})' at line 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO user VALUES ({username:'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})
code: "ER_PARSE_ERROR"
errno: 1064
sqlMessage: "You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ':'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})' at line 1"
sqlState: "42000"
index: 0
sql: "INSERT INTO user VALUES ({username:'data.name',tel:'data.tellphone',sexs:'data.gender',passwd:'data.password'})"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_PARSE_ERRORError"
pid: 29112
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:06:56,118 ERROR 11384 [-/127.0.0.1/-/39ms POST /userreg] nodejs.ER_DATA_TOO_LONGError: ER_DATA_TOO_LONG: Data too long for column 'tel' at row 1
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('data.name', 'data.tellphone', 'data.gender', 'data.password')
code: "ER_DATA_TOO_LONG"
errno: 1406
sqlMessage: "Data too long for column 'tel' at row 1"
sqlState: "22001"
index: 0
sql: "INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('data.name', 'data.tellphone', 'data.gender', 'data.password')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_DATA_TOO_LONGError"
pid: 11384
hostname: BN6BA2A2TJYV3R8

2020-10-29 15:07:56,221 ERROR 20292 [-/127.0.0.1/-/18ms POST /userreg] nodejs.ER_NO_DEFAULT_FOR_FIELDError: ER_NO_DEFAULT_FOR_FIELD: Field 'birthday' doesn't have a default value
    at Query.Sequence._packetToError (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Sequence.js:47:14)
    at Query.ErrorPacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\sequences\Query.js:79:18)
    at Protocol._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:291:23)
    at Parser._parsePacket (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:433:10)
    at Parser.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Parser.js:43:10)
    at Protocol.write (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\protocol\Protocol.js:38:16)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:88:28)
    at Socket.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Connection.js:526:10)
    at Socket.emit (events.js:315:20)
    at addChunk (_stream_readable.js:295:12)
    --------------------
    at Pool.query (C:\Users\Administrator\Desktop\server\node_modules\_mysql@2.18.1@mysql\lib\Pool.js:199:23)
    at C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:29:7
    at new Promise (<anonymous>)
    at Pool.<anonymous> (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:12:10)
    at Pool.ret [as query] (C:\Users\Administrator\Desktop\server\node_modules\_pify@2.3.0@pify\index.js:56:34)
    at RDSClient.proto._query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\client.js:38:20)
    at RDSClient.proto.query (C:\Users\Administrator\Desktop\server\node_modules\_ali-rds@3.4.0@ali-rds\lib\operator.js:54:29)
    at proto.query.next (<anonymous>)
    at onFulfilled (C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:65:19)
    at C:\Users\Administrator\Desktop\server\node_modules\_co@4.6.0@co\index.js:54:5
    sql: INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('zzz', '18108340587', '男', 'sdas123_')
code: "ER_NO_DEFAULT_FOR_FIELD"
errno: 1364
sqlMessage: "Field 'birthday' doesn't have a default value"
sqlState: "HY000"
index: 0
sql: "INSERT INTO `user`(`username`, `tel`, `sexs`, `passwd`) VALUES('zzz', '18108340587', '男', 'sdas123_')"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ER_NO_DEFAULT_FOR_FIELDError"
pid: 20292
hostname: BN6BA2A2TJYV3R8

2020-10-30 10:26:18,007 ERROR 8360 [-/192.168.5.151/-/141ms POST /upload] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\a76b4ac0-8582-40b6-886b-4fede140b371.mp4' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/mp4/a76b4ac0-8582-40b6-886b-4fede140b371.mp4'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.index (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:12:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\a76b4ac0-8582-40b6-886b-4fede140b371.mp4"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/mp4/a76b4ac0-8582-40b6-886b-4fede140b371.mp4"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:26:22,806 ERROR 8360 [-/192.168.5.151/-/7ms POST /uploads] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/img/d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.indexs (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:21:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/img/d1491dbf-ecba-4cad-afcb-d4e048e2dce1.jpg"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:26:26,850 ERROR 8360 [-/192.168.5.151/-/5ms POST /uploads] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/img/f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.indexs (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:21:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/img/f07da5ed-5877-429a-8b8a-d405349ed8ef.jpg"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:26:38,905 ERROR 8360 [-/192.168.5.151/-/5ms POST /uploads] nodejs.ENOENTError: ENOENT: no such file or directory, copyfile 'C:\Users\ADMINI~1\AppData\Local\Temp\egg-multipart-tmp\project\2020\10\30\10\3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg' -> 'C:\Users\Administrator\Desktop\xiaohongshu\server\app/public/img/3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg'
    at Object.copyFileSync (fs.js:1882:3)
    at UploadController.indexs (C:\Users\Administrator\Desktop\xiaohongshu\server\app\controller\upload.js:21:12)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\utils\index.js:44:21)
    at Object.classControllerMiddleware (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_egg-core@4.20.0@egg-core\lib\loader\mixin\controller.js:87:20)
    at Object.callFn (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\utils.js:12:21)
    at wrappedController (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\egg_router.js:322:18)
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
    at next (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:45:18)
    at C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_@eggjs_router@2.0.0@@eggjs\router\lib\router.js:190:18
    at dispatch (C:\Users\Administrator\Desktop\xiaohongshu\server\node_modules\_koa-compose@3.2.1@koa-compose\index.js:44:32)
errno: -4058
syscall: "copyfile"
code: "ENOENT"
path: "C:\\Users\\ADMINI~1\\AppData\\Local\\Temp\\egg-multipart-tmp\\project\\2020\\10\\30\\10\\3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg"
dest: "C:\\Users\\Administrator\\Desktop\\xiaohongshu\\server\\app/public/img/3c141691-832f-4c84-9c30-5424d8b1f6ae.jpg"
headers: {"Access-Control-Allow-Origin":"*","Access-Control-Allow-Credentials":"true","vary":"Origin"}
name: "ENOENTError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:40:29,205 ERROR 8360 [-/undefined/-/132ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNABORTEDError: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at clearBuffer (_stream_writable.js:542:7)
    at Socket.Writable.uncork (_stream_writable.js:338:7)
    at ServerResponse.OutgoingMessage.uncork (_http_outgoing.js:244:17)
    at connectionCorkNT (_http_outgoing.js:690:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
errno: "ECONNABORTED"
code: "ECONNABORTED"
syscall: "write"
headerSent: true
name: "ECONNABORTEDError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:40:29,572 ERROR 8360 [-/undefined/-/307ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:51:57,583 ERROR 8360 [-/undefined/-/201ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:51:57,611 ERROR 8360 [-/undefined/-/14ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNABORTEDError: write ECONNABORTED
    at afterWriteDispatched (internal/stream_base_commons.js:154:25)
    at writeGeneric (internal/stream_base_commons.js:145:3)
    at Socket._writeGeneric (net.js:786:11)
    at Socket._write (net.js:798:8)
    at doWrite (_stream_writable.js:403:12)
    at clearBuffer (_stream_writable.js:542:7)
    at Socket.Writable.uncork (_stream_writable.js:338:7)
    at ServerResponse.OutgoingMessage.uncork (_http_outgoing.js:244:17)
    at connectionCorkNT (_http_outgoing.js:690:8)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
errno: "ECONNABORTED"
code: "ECONNABORTED"
syscall: "write"
headerSent: true
name: "ECONNABORTEDError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:51:57,955 ERROR 8360 [-/undefined/-/287ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 10:53:32,304 ERROR 8360 [-/undefined/-/120ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 8360
hostname: SC-202006081301

2020-10-30 16:28:57,860 ERROR 10180 [-/undefined/-/309ms GET /public/mp4/14d73dd7-b201-42b9-8ea8-785eff98a285.mp4] nodejs.ECONNRESETError: write ECONNRESET
    at WriteWrap.onWriteComplete [as oncomplete] (internal/stream_base_commons.js:92:16)
errno: "ECONNRESET"
code: "ECONNRESET"
syscall: "write"
headerSent: true
name: "ECONNRESETError"
pid: 10180
hostname: SC-202006081301

